image:
  file: Dockerfile

tasks:
  - init: echo "Maybe some initial build commands here."
    command: python app.py

ports:
  - port: 8888
    onOpen: open-preview
  - port: 5000
    onOpen: open-preview
